# Numpy Linear Algebra

In [ ]:
3x + 2y = 15
4x + 6y = 30
x = ? = 3
y = ? = 3

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[3,2],[4,6]])
print(f"Array 1 = \n{arr1}")
arr2 = np.array([15,30])
print(f"Array 2 = \n{arr2}")

res = np.linalg.solve(arr1,arr2)
print(f"Result = {res}")

Array 1 = 
[[3 2]
 [4 6]]
Array 2 = 
[15 30]
Result = [3. 3.]


In [ ]:
3x + 5y + 10z = 20
4x + 7y + 13z = 30
2x + 17y + 3z = 40
x = ?
y = ?
z = ?

In [3]:
arr1 = np.array([[3,5,10],[4,7,13],[2,17,3]])
print(f"Array 1 = \n{arr1}")
arr2 = np.array([20,30,40])
print(f"Array 2 = \n{arr2}")

res = np.linalg.solve(arr1,arr2)
print(f"Result = {res}")

Array 1 = 
[[ 3  5 10]
 [ 4  7 13]
 [ 2 17  3]]
Array 2 = 
[20 30 40]
Result = [ 45.  -1. -11.]


In [4]:
(2*45) + (17*(-1)) + (3*(-11))

40

# Inverse of matrix

In [15]:
array = np.array([[3,2],[4,6]])
array

array([[3, 2],
       [4, 6]])

In [6]:
np.linalg.inv(array)

array([[ 0.6, -0.2],
       [-0.4,  0.3]])

# Copy of an Array

In [11]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1
arr2[0] = 1000
print(f"Array1 = {arr1}")
print(f"Array2 = {arr2}")

Array1 = [1000    2    3    4    5]
Array2 = [1000    2    3    4    5]


In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()
arr2[0] = 1000
print(f"Array1 = {arr1}")
print(f"Array2 = {arr2}")

Array1 = [1 2 3 4 5]
Array2 = [1000    2    3    4    5]


In [13]:
arr1 = np.array([
    [3,2],
    [4,6]
]
)
arr2 = arr1.copy()
arr2[0,1] = 1000
print(f"Array1 = \n{arr1}")
print(f"Array2 = \n{arr2}")

Array1 = 
[[3 2]
 [4 6]]
Array2 = 
[[   3 1000]
 [   4    6]]


In [14]:
li = [[1,2],[3,4]]
li2 = li.copy()
li2[0][1] = 1000
print(li,li2)

[[1, 1000], [3, 4]] [[1, 1000], [3, 4]]
