# Numpy
- Numpy - Numerical Computing / Operations

### Applications

- 1. Linear Algebra
- 2. Statistics
- 3. Probability
- 4. Trignometric Operations (sin, cos, tan, etc..)
- 5. Matrix
- 6. Image Processing(cv2)
- 7. Logarithmic

In [1]:
import numpy as np

In [2]:
li = [1,2.2,"3.3"]
li

[1, 2.2, '3.3']

# Creating Numpy Arrays

In [5]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [6]:
array = np.array([1,2,3,4,5.5])
array

array([1. , 2. , 3. , 4. , 5.5])

In [7]:
array = np.array([1,2,3,4,5.5,6,7])
array

array([1. , 2. , 3. , 4. , 5.5, 6. , 7. ])

In [8]:
array = np.array([1,2,3,4,5.5,6,7,3 + 6j])
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.5+0.j, 6. +0.j, 7. +0.j,
       3. +6.j])

In [9]:
array = np.array([1,2,3,4,5.5,6,7,3 + 6j,9.9,5])
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.5+0.j, 6. +0.j, 7. +0.j,
       3. +6.j, 9.9+0.j, 5. +0.j])

In [10]:
array = np.array((1,2,3,4,5.5,6,7,3 + 6j,9.9,5))
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.5+0.j, 6. +0.j, 7. +0.j,
       3. +6.j, 9.9+0.j, 5. +0.j])

In [11]:
array = np.array([1,2,3,4,5.5,"Learning Numpy Array"])
array

array(['1', '2', '3', '4', '5.5', 'Learning Numpy Array'], dtype='<U32')

In [12]:
array = np.array((1,2,3,4,5.5,6,7,3 + 6j,9.9,5,"Python"))
array

array(['1', '2', '3', '4', '5.5', '6', '7', '(3+6j)', '9.9', '5',
       'Python'], dtype='<U64')

# Change DataType of an array

In [13]:
array1 = np.array([1,2,3,4,5])
array1 

array([1, 2, 3, 4, 5])

In [14]:
array1 = np.array([1,2,3,4,5],dtype = int)
array1 

array([1, 2, 3, 4, 5])

In [15]:
array1 = np.array([1,2,3,4,5],dtype = float)
array1 

array([1., 2., 3., 4., 5.])

In [17]:
array1 = np.array([1,2,3,4,5],dtype = "complex")
array1 

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [18]:
array1 = np.array([1,2,3,4,5.5],dtype = float)
array1 

array([1. , 2. , 3. , 4. , 5.5])

In [21]:
array1 = np.array([1,2,3,4,5.5],dtype = int)
array1 

array([1, 2, 3, 4, 5])

In [22]:
li1 = [1,2,3,4,5]
li1

[1, 2, 3, 4, 5]

In [23]:
arr1 = np.array(li1)
arr1

array([1, 2, 3, 4, 5])

In [24]:
arr1 / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [25]:
arr1 ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [26]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [27]:
arr1 // 2

array([0, 1, 1, 2, 2], dtype=int32)

In [28]:
arr1 % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [30]:
array1 = np.array([1,2,3,4,5.5],dtype = complex)
array1

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.5+0.j])

In [32]:
int(1+2j)

TypeError: can't convert complex to int

In [31]:
arr1 = np.array([1,2,3,5+4j,5.5],dtype=int)
arr1

TypeError: can't convert complex to int

In [33]:
arr1 = np.array([1,2,3,5+4j,5.5],dtype=float)
arr1

TypeError: can't convert complex to float

In [34]:
arr1 = np.array([1,2,3,5+4j,5.5],dtype=complex)
arr1

array([1. +0.j, 2. +0.j, 3. +0.j, 5. +4.j, 5.5+0.j])

In [35]:
arr1 = np.array([1,2,3,5+4j,5.5])
arr1

array([1. +0.j, 2. +0.j, 3. +0.j, 5. +4.j, 5.5+0.j])

In [36]:
arr1 = np.array([1,2,3],dtype=str)
arr1

array(['1', '2', '3'], dtype='<U1')

In [37]:
arr1 = np.array([1,2,3,4.5,5.5],dtype=str)
arr1

array(['1', '2', '3', '4.5', '5.5'], dtype='<U3')

In [38]:
arr1 = np.array([1,2,3,4.5,5.5,6+5j],dtype=str)
arr1

array(['1', '2', '3', '4.5', '5.5', '(6+5j)'], dtype='<U6')

# Dimensions in array
## 1. 0-D array

In [39]:
arr = np.array(500)
arr

array(500)

In [40]:
arr = np.array(500)
print(f"Number of dimentions = {arr.ndim}")

Number of dimentions = 0


In [41]:
arr = np.array(100,float)
print(f"Number of dimentions = {arr.ndim}")

Number of dimentions = 0


In [42]:
arr = np.array(100,str)
print(f"Number of dimentions = {arr.ndim}")

Number of dimentions = 0


## 2. 1-Dimentional Array
- It is a collection of multiple 0-D arrays

In [43]:
arr = np.array([1,2,3,4,5])
print(f"Array = {arr}")
print(f"Number of dimentions = {arr.ndim}")

Array = [1 2 3 4 5]
Number of dimentions = 1


In [44]:
arr = np.array([1])
print(f"Array = {arr}")
print(f"Number of dimentions = {arr.ndim}")

Array = [1]
Number of dimentions = 1


In [45]:
arr = np.array(1)
print(f"Array = {arr}")
print(f"Number of dimentions = {arr.ndim}")

Array = 1
Number of dimentions = 0


## 3. 2-Dimentional Array
- It's a collection of multiple 1-D arrays

In [47]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3 4 5]
 [1 2 3 4 5]]
Number of dimentions = 2
The length of the array = 2
The shape of the array = (2, 5)


In [48]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Number of dimentions = 2
The length of the array = 3
The shape of the array = (3, 5)


In [49]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Number of dimentions = 2
The length of the array = 4
The shape of the array = (4, 5)


In [50]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[list([1, 2, 3, 4, 5]) list([1, 2, 3, 4, 5]) list([1, 2, 3, 4, 5])
 list([1, 2, 3, 4])]
Number of dimentions = 1
The length of the array = 4
The shape of the array = (4,)


<ipython-input-50-8c87b0360e3f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4]])


## 4. 3-Dimentional Array
- It's a collection of multiple 2-D array

In [52]:
arr = np.array([[[1,2,3,4,5]],[[1,2,3,4,5]]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[[1 2 3 4 5]]

 [[1 2 3 4 5]]]
Number of dimentions = 3
The length of the array = 2
The shape of the array = (2, 1, 5)


In [53]:
arr = np.array([[[1,2,3,4,5]],[[1,2,3,4,5]],[[1,2,3,4,5]]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]]
Number of dimentions = 3
The length of the array = 3
The shape of the array = (3, 1, 5)


In [54]:
arr = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]
Number of dimentions = 3
The length of the array = 2
The shape of the array = (2, 2, 5)


# Indexing and Slicing

In [55]:
li = [1,2,3,4,5]
li[3]

4

In [69]:
li[2:10]

[3, 4, 5]

In [56]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [57]:
arr[0]

1

In [58]:
arr[1]

2

In [59]:
arr[-1]

5

In [60]:
arr[-3]

3

In [61]:
arr

array([1, 2, 3, 4, 5])

In [62]:
arr[0:2]

array([1, 2])

In [63]:
arr[2:4]

array([3, 4])

In [65]:
arr[2:6]

array([3, 4, 5])

In [66]:
arr[2:10]

array([3, 4, 5])

In [70]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 5

In [71]:
arr

array([1, 2, 3, 4, 5])

In [72]:
arr[-4:-1]

array([2, 3, 4])

In [73]:
arr[-4:]

array([2, 3, 4, 5])

In [74]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [75]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(f"Array = \n{arr}")

Array = 
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [76]:
arr[1]

array([1, 2, 3, 4, 5])

In [77]:
arr[1][-1]

5

In [78]:
arr[1][2]

3

In [79]:
arr[1,2]

3

In [81]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [80]:
arr[1][2:]

array([3, 4, 5])

In [82]:
arr[2,-1]

5

In [83]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [84]:
arr[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [89]:
arr[:,2]

array([3, 3, 3])

In [90]:
arr[1:,2:4]

array([[3, 4],
       [3, 4]])

In [96]:
arr = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[[ 1  2  3  4  5]
  [ 1  2  3  4  5]
  [ 1  2  3  4  5]]

 [[10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]]]
Number of dimentions = 3
The length of the array = 2
The shape of the array = (2, 3, 5)


In [97]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [98]:
arr[0]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [99]:
arr[1]

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [100]:
arr[0,0,0]

1

In [101]:
arr[1,0,0]

10

In [102]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [103]:
arr[0,:,2:4]

array([[3, 4],
       [3, 4],
       [3, 4]])

In [104]:
arr[1,:,2:4]

array([[30, 40],
       [30, 40],
       [30, 40]])

In [105]:
arr[1,:,-1]

array([50, 50, 50])

In [106]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [107]:
arr[1,1,0]

10

In [108]:
arr[1,1,-1]

50

In [109]:
arr[:,:,:]

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [110]:
arr[:,:,1]

array([[ 2,  2,  2],
       [20, 20, 20]])

In [111]:
arr[:,:,1:3]

array([[[ 2,  3],
        [ 2,  3],
        [ 2,  3]],

       [[20, 30],
        [20, 30],
        [20, 30]]])

In [113]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [112]:
arr.shape

(2, 3, 5)

# Convert to n-D Array

In [114]:
arr = np.array([1,2,3,4,5])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[1 2 3 4 5]
Number of dimentions = 1
The length of the array = 5
The shape of the array = (5,)


In [116]:
arr = np.array([1,2,3,4,5],ndmin = 2)
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3 4 5]]
Number of dimentions = 2
The length of the array = 1
The shape of the array = (1, 5)


In [117]:
arr = np.array([1,2,3,4,5],ndmin = 1)
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[1 2 3 4 5]
Number of dimentions = 1
The length of the array = 5
The shape of the array = (5,)


In [118]:
arr = np.array([1,2,3,4,5],ndmin = 0)
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[1 2 3 4 5]
Number of dimentions = 1
The length of the array = 5
The shape of the array = (5,)


In [119]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3]
 [4 5 6]]
Number of dimentions = 2
The length of the array = 2
The shape of the array = (2, 3)


In [120]:
arr = np.array([[1,2,3],[4,5,6]],ndmin=1)
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3]
 [4 5 6]]
Number of dimentions = 2
The length of the array = 2
The shape of the array = (2, 3)


In [121]:
arr = np.array([[1,2,3],[4,5,6]],ndmin=3)
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[[1 2 3]
  [4 5 6]]]
Number of dimentions = 3
The length of the array = 1
The shape of the array = (1, 2, 3)


In [122]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5],ndmin=1)
print(f"Array = \n{arr}")

Array = 
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [123]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5],ndmin=2)
print(f"Array = \n{arr}")

Array = 
[[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]]


In [124]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5],ndmin=3)
print(f"Array = \n{arr}")

Array = 
[[[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]]]


In [125]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5],ndmin=4)
print(f"Array = \n{arr}")

Array = 
[[[[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]]]]


# reshape()

In [128]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[1 2 3 4 5 1 2 3 4 5 1 2]
Number of dimentions = 1
The length of the array = 12
The shape of the array = (12,)


In [129]:
arr = np.array([[1,2,3],[4,5,1],[2,3,4],[5,1,2]])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]
Number of dimentions = 2
The length of the array = 4
The shape of the array = (4, 3)


In [130]:
arr2 = np.array([[1,2,3],[4,5,1],[2,3,4],[5,1,2]])
arr2


array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2]])

In [131]:
arr2.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2]])

In [132]:
arr2.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5],
       [1, 2]])

In [133]:
arr2.reshape(2,6)

array([[1, 2, 3, 4, 5, 1],
       [2, 3, 4, 5, 1, 2]])

In [134]:
arr2.reshape(2,4)

ValueError: cannot reshape array of size 12 into shape (2,4)

In [135]:
arr2.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2]])

In [136]:
arr2.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2]])

In [137]:
arr2.reshape(1,12)

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2]])

In [139]:
arr2.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2]])

# 1-D to 3-D

In [140]:
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2])
print(f"Array = \n{arr}")
print(f"Number of dimentions = {arr.ndim}")
print(f"The length of the array = {len(arr)}")
print(f"The shape of the array = {arr.shape}")

Array = 
[1 2 3 4 5 1 2 3 4 5 1 2]
Number of dimentions = 1
The length of the array = 12
The shape of the array = (12,)


In [141]:
arr.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 5, 1]],

       [[2, 3, 4],
        [5, 1, 2]]])

In [142]:
arr.reshape(1,2,6)

array([[[1, 2, 3, 4, 5, 1],
        [2, 3, 4, 5, 1, 2]]])

In [144]:
arr.reshape(1,6,2)

array([[[1, 2],
        [3, 4],
        [5, 1],
        [2, 3],
        [4, 5],
        [1, 2]]])

In [145]:
arr.reshape(12,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[1]],

       [[2]]])

# Accessing elements from array using for loop

In [146]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [147]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [150]:
arr = [[1,2],[3,4],[5,6]]
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [152]:
arr = [[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]]
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
1
2
3
4
5
6


In [153]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

## np.nditer()

In [154]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [155]:
arr = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
arr

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [156]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
1
2
3
4
5
6


## np.ndenumerate()

In [157]:
arr = np.array([1,2,3,4,5])
for i,v in np.ndenumerate(arr):
    print(i,v)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [159]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
for i,v in np.ndenumerate(arr):
    print(i,v)

[[1 2]
 [3 4]
 [5 6]]
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6


In [162]:
arr = np.array([[[1,2,22],[3,4,44],[5,6,66]],[[1,2,22],[3,4,44],[5,6,66]]])
print(arr)
print()
for i,v in np.ndenumerate(arr):
    print(i,v)

[[[ 1  2 22]
  [ 3  4 44]
  [ 5  6 66]]

 [[ 1  2 22]
  [ 3  4 44]
  [ 5  6 66]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 22
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 44
(0, 2, 0) 5
(0, 2, 1) 6
(0, 2, 2) 66
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 22
(1, 1, 0) 3
(1, 1, 1) 4
(1, 1, 2) 44
(1, 2, 0) 5
(1, 2, 1) 6
(1, 2, 2) 66


# 4. zeros()
- np.zeros(shape , dtype = float)
- Return an array of zero value
- Weight Initialization
- Target column creation

In [163]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [164]:
arr = np.zeros(5,dtype=int)
arr

array([0, 0, 0, 0, 0])

In [165]:
arr = np.zeros(15,dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [167]:
False_col = np.zeros(15,dtype=int)
False_col

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [169]:
import pandas as pd
df = pd.DataFrame({"False_col":False_col})
df

False_col
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
12          0
13          0
14          0

In [170]:
arr = np.zeros((3,4),int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [171]:
pd.DataFrame(arr)

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0

##  5. ones()
- np.ones(shape, dtype=float)
- Return an array of one values

In [173]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [174]:
arr = np.ones(5,int)
arr

array([1, 1, 1, 1, 1])

In [175]:
pd.DataFrame(np.ones((5,5),int))

0  1  2  3  4
0  1  1  1  1  1
1  1  1  1  1  1
2  1  1  1  1  1
3  1  1  1  1  1
4  1  1  1  1  1

In [176]:
arr0 = np.zeros(500,int)
arr1 = np.ones(500,int)

new_arr = np.append(arr0,arr1)
df = pd.DataFrame({"Target_Column":new_arr})
df

Target_Column
0                0
1                0
2                0
3                0
4                0
..             ...
995              1
996              1
997              1
998              1
999              1

[1000 rows x 1 columns]