# Numpy-Stats
- 1. mean()
- 2. median()
- 3. mode()
- 4. var()
- 5. std()
- 6. min()
- 7. max()

In [3]:
import numpy as np

# 1. mean()

In [2]:
li = [1,2,3,4,5]
sum(li) / len(li)

3.0

In [19]:
arr = np.random.randint(10,20,size=9)
arr

array([14, 19, 17, 18, 11, 17, 15, 13, 14])

In [20]:
len(arr)

9

In [21]:
sum(arr)

138

In [22]:
sum(arr) / len(arr)

15.333333333333334

In [23]:
mean = np.mean(arr)
print(f"The array = {arr} and the mean = {mean}")

The array = [14 19 17 18 11 17 15 13 14] and the mean = 15.333333333333334


# median()

In [24]:
arr

array([14, 19, 17, 18, 11, 17, 15, 13, 14])

In [25]:
np.sort(arr)

array([11, 13, 14, 14, 15, 17, 17, 18, 19])

In [26]:
arr

array([14, 19, 17, 18, 11, 17, 15, 13, 14])

In [27]:
median = np.median(arr)
print(f"The sorted array = {np.sort(arr)} and the median = {median}")

The sorted array = [11 13 14 14 15 17 17 18 19] and the median = 15.0


In [28]:
arr = np.random.randint(10,20,size=10)
arr

array([14, 10, 16, 11, 16, 13, 10, 15, 13, 10])

In [29]:
np.sort(arr)

array([10, 10, 10, 11, 13, 13, 14, 15, 16, 16])

In [32]:
(13 + 13) / 2 

13.0

In [33]:
median = np.median(arr)
print(f"The sorted array = {np.sort(arr)} and the median = {median}")

The sorted array = [10 10 10 11 13 13 14 15 16 16] and the median = 13.0


# 3. std()

In [34]:
arr = np.random.randint(10,20,size=9)
arr

array([12, 11, 15, 13, 12, 12, 18, 12, 15])

In [35]:
np.std(arr)

2.1081851067789197

In [37]:
mean = np.mean(arr)
print(f"Mean of an array = {mean}")
median = np.median(np.sort(arr))
print(np.sort(arr))
print(f"Median of an array = {median}")
std = np.std(arr)
print(f"Standerd deviation of an array = {std}")

Mean of an array = 13.333333333333334
[11 12 12 12 12 13 15 15 18]
Median of an array = 12.0
Standerd deviation of an array = 2.1081851067789197


In [39]:
vari = np.var(arr)
print(f"Varaince of an array = {vari}")

Varaince of an array = 4.444444444444445


In [41]:
arr = np.random.randint(10,20,size=9)
print(f"The original array = {arr}")
print()
mean = np.mean(arr)
print(f"Mean of an array = {mean}")
print()
median = np.median(np.sort(arr))
print()
print("The sorted array = ",np.sort(arr))
print()
print(f"Median of an array = {median}")
std = np.std(arr)
print(f"Standerd deviation of an array = {std}")
print()
vari = np.var(arr)
print(f"Varaince of an array = {vari}")

The original array = [10 13 14 14 15 15 17 11 16]

Mean of an array = 13.88888888888889


The sorted array =  [10 11 13 14 14 15 15 16 17]

Median of an array = 14.0
Standerd deviation of an array = 2.1314806770278754

Varaince of an array = 4.54320987654321


In [43]:
arr = np.random.randint(10,20,size=9)
print(f"The original array = {arr}")
print()
mean = np.mean(arr)
print(f"Mean of an array = {mean}")
print()
median = np.median(np.sort(arr))
print()
print("The sorted array = ",np.sort(arr))
print()
print(f"Median of an array = {median}")
std = np.std(arr)
print(f"Standerd deviation of an array = {std}")
print()
vari = np.var(arr)
print(f"Varaince of an array = {vari}")
print()
min_val = np.min(arr)
print(f"Min value of an array = {min_val}")
print()
max_val = np.max(arr)
print(f"Max value of an array = {max_val}")

The original array = [19 12 10 14 16 16 10 18 16]

Mean of an array = 14.555555555555555


The sorted array =  [10 10 12 14 16 16 16 18 19]

Median of an array = 16.0
Standerd deviation of an array = 3.095197394929804

Varaince of an array = 9.580246913580247

Min value of an array = 10

Max value of an array = 19


# Mode 
- Most frequent value of an array

In [44]:
from scipy import stats

In [46]:
arr = np.random.randint(10,20,size=9)
print(f"The original array = {arr}")
print()
mode = stats.mode(arr)
print(f"The mode of an array = {mode}")

The original array = [17 19 19 15 15 13 15 13 16]

The mode of an array = ModeResult(mode=array([15]), count=array([3]))


In [47]:
arr = np.array([1,1,1,2,3,4,5,1,1,1])
print(f"The original array = {arr}")
print()
mode = stats.mode(arr)
print(f"The mode of an array = {mode}")

The original array = [1 1 1 2 3 4 5 1 1 1]

The mode of an array = ModeResult(mode=array([1]), count=array([6]))


In [49]:
mode[0][0]

1

In [53]:
arr = np.array([[12, 5, 5],[5, 20, 30],[12, 5 , 4]])
print(f"The original array = \n{arr}")
print()
mode = stats.mode(arr)
print(f"The mode of an array = {mode}")

The original array = 
[[12  5  5]
 [ 5 20 30]
 [12  5  4]]

The mode of an array = ModeResult(mode=array([[12,  5,  4]]), count=array([[2, 2, 1]]))


In [59]:
mode[1][0][-1]

1

In [60]:
arr = np.array([10,20,30,40])
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [61]:
np.cbrt(arr)

array([2.15443469, 2.71441762, 3.10723251, 3.41995189])

In [62]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [63]:
np.full(100,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])