In [1]:
import numpy as np
import pandas as pd

# 1. reshape

In [4]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# 2. np.nditer()

In [8]:
arr = np.array([1,2,3,4,5,6])
for val in np.nditer(arr.reshape(3,2)):
    print(val)

1
2
3
4
5
6


# 3. np.ndenumerate()

In [10]:
arr = np.array([1,2,3,4,5,6])
for ind,val in np.ndenumerate(arr.reshape(3,2)):
    print(ind,val)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6


# 4. zeros()

In [11]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros(5,int)
arr

array([0, 0, 0, 0, 0])

In [13]:
arr = np.zeros((3,4),int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 5. ones()

In [14]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [15]:
arr = np.ones(5,int)
arr

array([1, 1, 1, 1, 1])

In [16]:
arr = np.ones((3,4),int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 6. arange()

In [17]:
range(1,10)

range(1, 10)

In [18]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [21]:
arr = np.arange(0,20,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [23]:
arr = np.arange(-5,6)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

# 7. linspace()

In [24]:
arr = np.linspace(1,50)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [25]:
arr = np.linspace(1,50,10)
arr

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
arr = np.linspace(1,100,10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [32]:
17.33333333 - 11.88888889 

5.444444439999998

In [33]:
arr = np.linspace(1,100,10,retstep = True)
arr

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [34]:
arr = np.linspace(1,50,10,retstep=True)
arr

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [35]:
arr = np.linspace(1,50,retstep=True)
arr

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

# eye()
- It will return an array with ones on diagonal and zeros elsewhere
- np.eye(shape,dtype)

In [36]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr = np.eye(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
arr = np.eye(5,6,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [40]:
arr = np.eye(10,5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 9. identity()
- It will return identity matrix
- num of rows == num of columns
- np.identity(value)

In [41]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr = np.identity(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
arr = np.identity(1,dtype=int)
arr

array([[1]])

In [44]:
arr = np.identity(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
arr = np.identity(1,5,dtype=int)
arr

TypeError: identity() got multiple values for argument 'dtype'

# 10. random()
- Used to generate random numbers
- 1. rand()
- 2. randint()
- 3. randn()
- 4. randf()

# 10.1 rand()
- It will return a values between 0 and 1

In [48]:
arr = np.random.rand(5)
arr

array([0.38028792, 0.9460125 , 0.18183567, 0.58137393, 0.33389186])

In [50]:
arr = np.random.rand(3,3)
arr

array([[0.06862045, 0.80392536, 0.87989318],
       [0.08749755, 0.63313919, 0.74315288],
       [0.0848745 , 0.66587941, 0.59680432]])

In [59]:
df = pd.DataFrame(np.random.rand(3,3))
df

0         1         2
0  0.516414  0.406453  0.484247
1  0.370220  0.088611  0.864314
2  0.558363  0.721078  0.137676

# 10.2 randint()

In [56]:
arr = np.random.randint(1,5)
arr

4

In [63]:
arr = np.random.randint(1,50,size=10)
arr

array([48,  7, 23, 37, 26, 40, 43,  5, 43,  7])

In [66]:
arr = np.random.randint(1,50,size=(10,10))
arr

array([[24,  1, 21,  2, 49, 18, 20, 22,  6, 15],
       [45,  2, 25, 40, 23, 25, 19, 36, 24, 24],
       [47, 29,  4, 47,  9,  1, 15, 32,  3, 17],
       [44, 26,  5, 31, 42,  5,  5, 15, 19, 38],
       [19,  4, 18, 23, 20, 21, 15, 38, 17, 40],
       [32, 33, 27, 38,  1, 20, 25, 13, 36, 31],
       [17, 41, 12, 18,  6, 22, 21,  8, 27, 14],
       [43, 24, 34, 24, 16, 39, 14, 46, 14, 26],
       [35, 38, 37, 39, 40, 20, 35, 40, 33, 47],
       [ 8, 49, 28, 49,  8, 29, 42,  5, 45, 34]])

In [67]:
df = pd.DataFrame(np.random.randint(1,50,size=(10,10)))
df

0   1   2   3   4   5   6   7   8   9
0  14   5  47  47  29  15   2  11  40  39
1  20  30   1  39   8   3  42   8  16  41
2   2  12  17  42   5  17  37  31  37  43
3  19  44   4  22  25  46  40  42  26   2
4  40  14  24   3   9  29  49  19   9  47
5  45  12  33   9  18  39  25  36  19  46
6  38  10  40   2   2  42  43  30  23  40
7  27   1  29  48  28  49  30   7  23  23
8  28  28  15  24   5   9   7  42  37  30
9  13  12  40  27  41  41  11   3  41   6

# 10.3 randn()
- It will return values which are normally distributed

In [68]:
arr = np.random.randn(10)
arr

array([-0.08926359,  0.04932617,  1.67082871, -0.87010004, -1.04686584,
       -0.28735468,  0.00181606,  1.28618903,  0.86296605, -1.01389584])

# 10.4 ranf()
- Return Values between 0 and 1


In [69]:
arr = np.random.ranf(5)
arr

array([0.82885159, 0.71029319, 0.27751079, 0.09082622, 0.05346136])

In [70]:
dict_np_functios = {
    "Zeros" : np.zeros(10,int),
    "Ones" : np.ones(10,int),
    "Arange" : np.arange(101,111),
    "Linspace" : np.linspace(10,20,num = 10),
    "Randint" : np.random.randint(10,50,size=10),
    "Randn" : np.random.randn(10)
}
dict_np_functios

{'Zeros': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'Ones': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'Arange': array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110]),
 'Linspace': array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 'Randint': array([31, 39, 35, 25, 18, 32, 20, 22, 43, 25]),
 'Randn': array([-2.38780243,  0.76142056,  0.19658921, -0.59836567, -0.66935011,
        -0.71628583, -0.12829634,  0.06768339, -2.03905897,  0.44692474])}

In [71]:
df = pd.DataFrame(dict_np_functios)
df

Zeros  Ones  Arange   Linspace  Randint     Randn
0      0     1     101  10.000000       31 -2.387802
1      0     1     102  11.111111       39  0.761421
2      0     1     103  12.222222       35  0.196589
3      0     1     104  13.333333       25 -0.598366
4      0     1     105  14.444444       18 -0.669350
5      0     1     106  15.555556       32 -0.716286
6      0     1     107  16.666667       20 -0.128296
7      0     1     108  17.777778       22  0.067683
8      0     1     109  18.888889       43 -2.039059
9      0     1     110  20.000000       25  0.446925

# 11. sort()

In [74]:
arr = np.array(np.random.randint(1,50,size=5))
arr

array([31, 42, 31, 30, 21])

In [75]:
np.sort(arr)

array([21, 30, 31, 31, 42])

In [77]:
arr = np.array([[5,2,8,7,9],[5,2,8,7,9]])
np.sort(arr)

array([[2, 5, 7, 8, 9],
       [2, 5, 7, 8, 9]])

# append()
- syntax = np.append(array1,array2,axis=none)
- axis = 0 === Rows
- axis = 1 === Col

In [78]:
li = [1,2,3]
li.append(1000)
li

[1, 2, 3, 1000]

In [79]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,22,33,44,55])
new_arr = np.append(arr1,arr2)
new_arr

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

In [80]:
arr1 = np.array([1,2,3,4,5])
# arr2 = np.array([11,22,33,44,55])
new_arr = np.append(arr1,50)
new_arr

array([ 1,  2,  3,  4,  5, 50])

In [81]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
new_arr = np.append(arr1,arr2)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]


array([ 1,  2,  3,  4, 11, 22, 33, 44])

In [82]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
new_arr = np.append(arr1,arr2,axis=0)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]


array([[ 1,  2],
       [ 3,  4],
       [11, 22],
       [33, 44]])

In [83]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
new_arr = np.append(arr1,arr2,axis=1)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]


array([[ 1,  2, 11, 22],
       [ 3,  4, 33, 44]])

# 13. concatenate()
- np.concatenate([arr1, arr2, ............, arrN],axis=0)

In [84]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
new_arr = np.concatenate([arr1,arr2]) # axis = 0 (Adding rows)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]


array([[ 1,  2],
       [ 3,  4],
       [11, 22],
       [33, 44]])

In [86]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
new_arr = np.concatenate([arr1,arr2],axis=1) # axis = 1 (Adding col)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]


array([[ 1,  2, 11, 22],
       [ 3,  4, 33, 44]])

In [87]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
arr3 = np.array([[111,222],[333,444]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
print(f"Array 3 = \n{arr3}")
new_arr = np.concatenate([arr1,arr2,arr3],axis=0)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]
Array 3 = 
[[111 222]
 [333 444]]


array([[  1,   2],
       [  3,   4],
       [ 11,  22],
       [ 33,  44],
       [111, 222],
       [333, 444]])

In [88]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
arr3 = np.array([[111,222],[333,444]])
print(f"Array 1 = \n{arr1}")
print(f"Array 2 = \n{arr2}")
print(f"Array 3 = \n{arr3}")
new_arr = np.concatenate([arr1,arr2,arr3],axis=1)
new_arr

Array 1 = 
[[1 2]
 [3 4]]
Array 2 = 
[[11 22]
 [33 44]]
Array 3 = 
[[111 222]
 [333 444]]


array([[  1,   2,  11,  22, 111, 222],
       [  3,   4,  33,  44, 333, 444]])

# 15. np.ceil()

In [90]:
np.ceil(3.1)

4.0

In [91]:
np.ceil(3.5)

4.0

In [92]:
np.ceil(3.9)

4.0

In [93]:
np.ceil(4)

4.0

In [94]:
np.ceil([4,4.1,5.7,6.6,9.9])

array([ 4.,  5.,  6.,  7., 10.])

In [100]:
arr = np.array([1.2,3.2,4.7,9.9,6.7])
np.ceil(arr)

array([ 2.,  4.,  5., 10.,  7.])

# 15. np.floor()

In [95]:
5 / 2

2.5

In [96]:
5 // 2

2

In [97]:
np.floor(3.4)

3.0

In [98]:
np.floor(3.9)

3.0

In [99]:
np.floor(9)

9.0

In [101]:
arr = np.array([1.2,3.2,4.7,9.9,6.7])
np.floor(arr)

array([1., 3., 4., 9., 6.])

In [102]:
arr = np.array([[1.2,3.2,4.7],[9.9,6.7,7.7]])
np.floor(arr)

array([[1., 3., 4.],
       [9., 6., 7.]])

# 16. np.around()

In [103]:
round(1.12345677,2)

1.12

In [106]:
round(1.77945677,2)

1.78

In [107]:
np.around(1.77945677,2)

1.78

In [111]:
np.around([1.12345,5.67890,5.43325],2)

array([1.12, 5.68, 5.43])

# 17. np.where()
- np.where(condition)

In [113]:
li = [1,2,3,1,2,3,1,2,3]
ind_li = [ind for ind,val in enumerate(li) if val == 2]
ind_li

[1, 4, 7]

In [114]:
arr = np.array(li)
new_arr = np.where(arr == 2)
new_arr

(array([1, 4, 7], dtype=int64),)

In [115]:
type(new_arr)

tuple

In [120]:
new_arr[0].tolist()

[1, 4, 7]

In [121]:
arr = np.array(li)
new_arr = np.where(arr != 2)
new_arr[0].tolist()

[0, 2, 3, 5, 6, 8]

In [122]:
arr = np.array(li)
new_arr = np.where(arr > 2)
new_arr[0].tolist()

[2, 5, 8]

# Convert array to list

In [123]:
array = np.random.randint(10,20,size=10)
array

array([12, 17, 17, 10, 14, 15, 16, 17, 17, 11])

In [124]:
type(array)

numpy.ndarray

In [125]:
list(array)

[12, 17, 17, 10, 14, 15, 16, 17, 17, 11]

In [126]:
array.tolist()

[12, 17, 17, 10, 14, 15, 16, 17, 17, 11]

# Numerical Operations

In [129]:
array = np.random.randint(10,20,size=5)
array

array([13, 15, 16, 13, 12])

In [131]:
array + 2

array([15, 17, 18, 15, 14])

In [132]:
array - 2

array([11, 13, 14, 11, 10])

In [133]:
array * 2

array([26, 30, 32, 26, 24])

In [134]:
array / 2

array([6.5, 7.5, 8. , 6.5, 6. ])

In [135]:
array // 2

array([6, 7, 8, 6, 6], dtype=int32)

In [138]:
array % 2

array([1, 1, 0, 1, 0], dtype=int32)

In [139]:
array ** 2

array([169, 225, 256, 169, 144], dtype=int32)

# Matrix addition

In [141]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[10,20],[30,40]])
print(f"Arr1 = \n{arr1}")
print(f"Arr2 = \n{arr2}")
arr3 = arr2 + arr1
print(f"Arr3 = \n{arr3}")

Arr1 = 
[[1 2]
 [3 4]]
Arr2 = 
[[10 20]
 [30 40]]
Arr3 = 
[[11 22]
 [33 44]]


# np.add()

In [142]:
np.add(arr1,arr2)

array([[11, 22],
       [33, 44]])

# Matrix multiplication

In [143]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[10,20],[30,40]])
print(f"Arr1 = \n{arr1}")
print(f"Arr2 = \n{arr2}")
arr3 = np.multiply(arr1,arr2)
print(f"Arr3 = \n{arr3}")

Arr1 = 
[[1 2]
 [3 4]]
Arr2 = 
[[10 20]
 [30 40]]
Arr3 = 
[[ 10  40]
 [ 90 160]]


# Matrix Dot Product

In [144]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[10,20],[30,40]])
print(f"Arr1 = \n{arr1}")
print(f"Arr2 = \n{arr2}")
arr3 = np.dot(arr1,arr2)
print(f"Arr3 = \n{arr3}")

Arr1 = 
[[1 2]
 [3 4]]
Arr2 = 
[[10 20]
 [30 40]]
Arr3 = 
[[ 70 100]
 [150 220]]
