# Numpy-Trigonometry

In [1]:
import numpy as np

In [3]:
pi_value = np.pi
print(f"The value of pi = {pi_value}")

The value of pi = 3.141592653589793


In [4]:
sin_30 = np.sin(pi_value / 6) # sin(30)
sin_30

0.49999999999999994

In [5]:
sin_45 = np.sin(pi_value / 4) # sin(45)
sin_45

0.7071067811865476

In [6]:
1/np.sqrt(2)

0.7071067811865475

In [7]:
sin_90 = np.sin(pi_value / 2) # sin(90)
sin_90

1.0

In [8]:
sin_180 = np.sin(pi_value) # sin(180)
sin_180

1.2246467991473532e-16

In [9]:
cos_60 = np.cos(pi_value / 3) # cos(60)
cos_60

0.5000000000000001

In [10]:
tan_60 = np.tan(pi_value / 3) # cos(60)
tan_60

1.7320508075688767

In [11]:
np.sqrt(3)

1.7320508075688772

# Degree to redian

In [12]:
np.deg2rad(30)

0.5235987755982988

In [13]:
np.deg2rad(90)

1.5707963267948966

In [14]:
arr = np.deg2rad([0,30,45,60,90])
arr

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [15]:
np.sin(arr)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [16]:
np.cos(arr)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

# Redian to Degree

In [17]:
radian = np.array([0.0, 0.52359878, 0.78539816, 1.04719755, 1.57079633])
degrees = np.rad2deg(radian)
degrees

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])